# Generated by Django 4.2.1 on 2023-07-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regmod',
        ),
    ]
