# Generated by Django 4.2.1 on 2023-07-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_app', '0002_delete_regmod'),
    ]

    operations = [
        migrations.CreateModel(
            name='regmod1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('num', models.IntegerField()),
                ('em', models.EmailField(max_length=254)),
                ('im', models.FileField(upload_to='bank_app/static')),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
