# Generated by Django 4.2.1 on 2023-07-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logmod1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('pswd', models.IntegerField()),
            ],
        ),
    ]
