# Generated by Django 4.2.1 on 2023-07-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_logmod1'),
    ]

    operations = [
        migrations.AddField(
            model_name='regmod1',
            name='balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
