# Generated by Django 4.2.1 on 2023-07-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_regmod1_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='addamount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addamount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='regmod1',
            name='ac_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
