# Generated by Django 4.2.1 on 2023-07-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_addamount_regmod1_ac_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addamount',
            old_name='addamount',
            new_name='amount',
        ),
    ]
