# Generated by Django 4.2.1 on 2023-07-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_ministatement_withdrawamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regmod1',
            name='pin',
            field=models.CharField(max_length=30),
        ),
    ]
