# Generated by Django 4.2.1 on 2023-07-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0012_addamount_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawamount',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
