# Generated by Django 4.2.1 on 2023-07-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0014_tablesmod'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesmod',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
